#!/bin/zsh

# eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

export PATH=/../usr/local/smlnj/bin:$PATH
export PATH=$PATH:$(go env GOPATH)/bin
export STARSHIP_CONFIG=$HOME/.config/Dotfiles/plugins/starship/starship.toml
