#!/bin/zsh
ALIASES="$HOME/.config/Dotfiles/aliases"

source "$ALIASES/bash_aliases"
source "$ALIASES/cars"
source "$ALIASES/ezgit"
source "$ALIASES/nvim/nvim"

if [[ "$OSTYPE" == "darwin"* ]]; then
    source "$ALIASES/macos_aliases"
elif [[ -f /etc/arch-release ]] || command -v pacman &>/dev/null; then
    source "$ALIASES/linux_aliases"
elif [[ -f /etc/debian_version ]] || command -v apt &>/dev/null; then
    source "$ALIASES/linux_aliases"
fi
