#!/bin/zsh

#___________OTHERS____________#
alias rst='exec zsh'
alias cl='clear'

#_____________LS______________#
alias ls='lsd --group-dirs first --color=auto'
alias l='lsd --group-dirs first --color=auto -1'
alias ll='lsd -l --group-dirs first --color=auto'
alias la='lsd -la --group-dirs first --color=auto'

#_________NAVIGATION___________#
alias ..='cd ..'
alias ...='cd ../..'

#____________PYTHON____________#
alias pip='pip3'
alias python='python3'
alias py='python3'

#_____________APPS_____________#

alias todo='~/.todo/todo-cli'
