#!/bin/zsh

# Search in files and open in editor
search() {
    if [ $# -eq 0 ]; then
        echo "Usage: search <search term>"
        return 1
    fi

    query="$*"
    selected=$(rg "$query" --line-number | fzf --preview "echo {}" | awk -F ":" '{print $1":"$2}')

    if [ -n "$selected" ]; then
        file=$(echo "$selected" | cut -d':' -f1)
        line=$(echo "$selected" | cut -d':' -f2)
        ${EDITOR:-nvim} "$file" +"$line"
    fi
}
