#!/bin/zsh
DOTFILE_DIR="$HOME/.config/Dotfiles/"

alias n="$DOTFILE_DIR/aliases/nvim/nvim-script.sh"
alias sn="$DOTFILE_DIR/aliases/nvim/nvim-sudo.sh"

prePath="nvims/"
ultra="nvim-ultralight"
light="nvim-light"
large="nvim-large"

nvimChoice="${ultra}"

choice="${prePath}${nvimChoice}"

export NVIM_APPNAME="${choice}"
